name: Scheduled Job Crawling

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo "========================================="
          echo "🚀 USING REQUIREMENTS-CRAWLER.TXT (v2)"
          echo "========================================="
          cd backend
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la *.txt
          echo ""
          echo "Contents of requirements-crawler.txt:"
          cat requirements-crawler.txt
          echo ""
          echo "Installing dependencies..."
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements-crawler.txt
          echo ""
          echo "Installing Playwright browsers..."
          playwright install --with-deps chromium

      - name: Run crawlers
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          cd backend
          python -c "from crawlers.un_careers_spider import crawl_un_careers_sync; print(crawl_un_careers_sync())"
          python -c "from crawlers.undp_spider import crawl_undp_sync; print(crawl_undp_sync())"
          python -c "from crawlers.unicef_spider import crawl_unicef_sync; print(crawl_unicef_sync())"

      - name: Notify on failure
        if: failure()
        run: echo "Crawling failed. Check logs."

